# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Test PyFlexFloat library
on: [push, pull_request]

jobs:
  test:
    name: Build and test package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Build
        run: pip install .
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test
        run: ./test/test.py
